# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonathan/Documents/AU/7sem/gsa/projects/project-1-c-o-no-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonathan/Documents/AU/7sem/gsa/projects/project-1-c-o-no-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonathan/Documents/AU/7sem/gsa/projects/project-1-c-o-no-1/CMakeFiles /home/jonathan/Documents/AU/7sem/gsa/projects/project-1-c-o-no-1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonathan/Documents/AU/7sem/gsa/projects/project-1-c-o-no-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named naive

# Build rule for target.
naive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 naive
.PHONY : naive

# fast build rule for target.
naive/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/naive.dir/build.make CMakeFiles/naive.dir/build
.PHONY : naive/fast

#=============================================================================
# Target rules for targets named lin

# Build rule for target.
lin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lin
.PHONY : lin

# fast build rule for target.
lin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lin.dir/build.make CMakeFiles/lin.dir/build
.PHONY : lin/fast

src/lin.o: src/lin.c.o
.PHONY : src/lin.o

# target to build an object file
src/lin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lin.dir/build.make CMakeFiles/lin.dir/src/lin.c.o
.PHONY : src/lin.c.o

src/lin.i: src/lin.c.i
.PHONY : src/lin.i

# target to preprocess a source file
src/lin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lin.dir/build.make CMakeFiles/lin.dir/src/lin.c.i
.PHONY : src/lin.c.i

src/lin.s: src/lin.c.s
.PHONY : src/lin.s

# target to generate assembly for a file
src/lin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lin.dir/build.make CMakeFiles/lin.dir/src/lin.c.s
.PHONY : src/lin.c.s

src/naive.o: src/naive.c.o
.PHONY : src/naive.o

# target to build an object file
src/naive.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/naive.dir/build.make CMakeFiles/naive.dir/src/naive.c.o
.PHONY : src/naive.c.o

src/naive.i: src/naive.c.i
.PHONY : src/naive.i

# target to preprocess a source file
src/naive.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/naive.dir/build.make CMakeFiles/naive.dir/src/naive.c.i
.PHONY : src/naive.c.i

src/naive.s: src/naive.c.s
.PHONY : src/naive.s

# target to generate assembly for a file
src/naive.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/naive.dir/build.make CMakeFiles/naive.dir/src/naive.c.s
.PHONY : src/naive.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... lin"
	@echo "... naive"
	@echo "... src/lin.o"
	@echo "... src/lin.i"
	@echo "... src/lin.s"
	@echo "... src/naive.o"
	@echo "... src/naive.i"
	@echo "... src/naive.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

